name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      stepsOutput: ${{ steps.publish.outputs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./NeoBus/NeoBus.csproj

      - name: Build
        run: dotnet build ./NeoBus/NeoBus.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./NeoBus/NeoBus.csproj --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ./NeoBus/NeoBus.csproj --no-build --configuration Release --output nupkgs

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Set output variable
        id: set-output
        run: echo "NUPKG_PATH=$(find ${{ github.workspace }}/nupkgs -name *.nupkg)" >> $GITHUB_ENV
        shell: bash

      - name: Publish to NuGet.org
        run: dotnet nuget push ${{ needs.build.outputs.stepsOutput.NUPKG_PATH }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PROFILE_TOKEN }}" >> $HOME/.npmrc
          dotnet nuget add source "https://nuget.pkg.github.com/OWNER/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.PROFILE_TOKEN }} --store-password-in-clear-text
          dotnet nuget push ${{ needs.build.outputs.stepsOutput.NUPKG_PATH }} --source github --no-service-endpoint
